baseurl: "https://datascience-euf-spring23.netlify.app/"
languageCode: "en-us"
title: "Data Science (SpSe23)"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:slug/"
  notes: "/notes/:slug/"
  tutorial: "/tutorial/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Material
      url: "material/"
      weight: 3
    - name: Categories
      url: "categories/"
      weight: 4
    - name: Tags
      url: "tags/"
      weight: 5

params:
  description: "Course website for the course 'Data Science using R', Spring Semester 2023."
  footer: "&copy; [Claudius Gräbner-Radkowitsch](https://claudius-graebner.com/) 2021 -- {Year} | [EUF](https://www.uni-flensburg.de/en/pluralist-economics) | [Github](https://github.com/graebnerc) | [Twitter](https://twitter.com/ClaudiusGrabner) | [OrcID](https://orcid.org/0000-0003-4065-4722) \\\n Created with [blogdown](https://github.com/rstudio/blogdown) using the [Xmin theme](https://github.com/yihui/hugo-xmin)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
